language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: oddjobz
  on:
    branch: master
  password:
    secure: TyZAmuwuXnN2FLOtPzKzBHqojiIcLhPO3PrAu+oNNRe98uBNw6eyZOuzPs+Nj2WzSX7GJZtJHtbb2oNbFAycIlD2sF2Od5ZIte89JBXLrGrpfgoSgNTGF82u5G+u7GL7/dSTI+RQ/UguASOuxdrpO+aUgPg3SzmgxkRhQ7sUtyEGoeJEiPUTDMMDpOqmsrjfsj0G09NLJcp2Lfz9yGWMHIfi6rL16msG9LAZGXhmwDplEqGq2zZmwEDENoX1RmXoTlBgCzsb71nXCzK6k3kkTRdeQDZX3eq8uqwn/epDJo13qEb2brL3ggZbkm67OhjcNW8of8fvmWJaywNiYpT5CdjaKTQTtDyEYu+4xAR+P3QDCZ6DTbAGzkwM5Myo5GReUDvQQK9cMPSK2kR9li06BRatVc2F8mnDe1t62ePXx/BUZpAkJCyqmqRUmWKmmGm1DYure38Lw7wgoVoDZtZrLJlpme9TSyFzkDpnjmu/FZouoQHodub5YknmTw0ffAUB3tT8MwLfbXG40hUaFvEI9Pj/k0sgNWvQx57gOyGqCHvGwo/kqGNHW23+Tmjp11uot4tj2H8g34bt/pEgulRJcCPrjQXJ7sfREwIbbt3dhuh7H9DwliXtQBfpPmexggg0EMGIvH9Dz8lFnY7Hc/elCqabfeewbGKpcxZIusn3kbo=
notifications:
  slack:
    secure: grqekwL6qjozcKN01tVn2vNTYyb7uQtRzoL3naRDSmYXYHqqTGjzF2QjS0RyhFEIdrHFj5b96EgVVfdSTF7GdqTJadnmruc4EmITTsk10bvAfio1Kzk7RiFt/HNXUumdNRYZj8aOEkxEK2NLuc+YCU5XQa9lsoef/AGspbZgshOzN0pDOuSkqyhU5e7XVIS8RiuLl9qgEtwqvsQuuZI2TuOHeuaFBxIZNifAJa5KkuxcL5q9kvJC2nKmH8rfy8x5/QsyAvUewvB4/ituQsZZZSopYAuD/cPlNaLrp6KtkrA1AUfvHIWiVjpjS01J7Q/dCP1+VPvkoGGuilzPOgU8wwfOtxy67aWGvycshZORVjJLOfAYh9HrRgPZvukjXRWt66IC1Z2orjTKy6UMYC1PI9G+HPO7PzAtRR2DH1wOlpY5Lu6daL/A2BH2D2yhpLKVFCd3uDSAohpIkA2alVgS4PpIWE8D4CLdARRWa8amBQHF+6DIggmscubtXyvuZIJp8cfQ9uICvYzuuQSYefv4GnxL2u6PGUw5bmmfTj5uTS9DnReO60QJRZrmvMcryats1+IHJFzHUGVN1wnQm3P/kPHIlC/pAbJ02saLsfW8Jmx9LK3JniMidRZTMpFqlAnUEiQ7rgcm1sPP4BO6lErL1BJxkXW72GJtNyOz08CkCoY=
