language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install tox
script:
- tox
notifications:
- slack: iflexrtsstudio:DA5mI8cXzaRdkanMPINNpECW
deploy:
  provider: pypi
  user: "oddjobz"
  password:
    secure: TyZAmuwuXnN2FLOtPzKzBHqojiIcLhPO3PrAu+oNNRe98uBNw6eyZOuzPs+Nj2WzSX7GJZtJHtbb2oNbFAycIlD2sF2Od5ZIte89JBXLrGrpfgoSgNTGF82u5G+u7GL7/dSTI+RQ/UguASOuxdrpO+aUgPg3SzmgxkRhQ7sUtyEGoeJEiPUTDMMDpOqmsrjfsj0G09NLJcp2Lfz9yGWMHIfi6rL16msG9LAZGXhmwDplEqGq2zZmwEDENoX1RmXoTlBgCzsb71nXCzK6k3kkTRdeQDZX3eq8uqwn/epDJo13qEb2brL3ggZbkm67OhjcNW8of8fvmWJaywNiYpT5CdjaKTQTtDyEYu+4xAR+P3QDCZ6DTbAGzkwM5Myo5GReUDvQQK9cMPSK2kR9li06BRatVc2F8mnDe1t62ePXx/BUZpAkJCyqmqRUmWKmmGm1DYure38Lw7wgoVoDZtZrLJlpme9TSyFzkDpnjmu/FZouoQHodub5YknmTw0ffAUB3tT8MwLfbXG40hUaFvEI9Pj/k0sgNWvQx57gOyGqCHvGwo/kqGNHW23+Tmjp11uot4tj2H8g34bt/pEgulRJcCPrjQXJ7sfREwIbbt3dhuh7H9DwliXtQBfpPmexggg0EMGIvH9Dz8lFnY7Hc/elCqabfeewbGKpcxZIusn3kbo=
