language: python

python:
- "3.6"

install:
- pip install -r requirements.txt
- pip install tox

script:
- tox

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
- slack: iflexrtsstudio:DA5mI8cXzaRdkanMPINNpECW
