language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install
- pipenv install --dev
script:
- tox
deploy:
  provider: pypi
  user: "oddjobz"
  on:
    branch: master
  password:
    secure: LfuJ+1W9v1jIajSyh3MEOwbeXqs7q4UWUoTCcGO3FiAKhSt2TNpSTsTwB0sI25fAiRc970C/R7ftqi7ihwbhIaKmkWTIIwjJ7vyGZ3X6mhgDWafO0EwvK7CT/t6v68qQCIwZUfvgBHrgq9Cmc1jF7BYa5kxG9hcZKznHXJgUUkeUS1JNT58xalVg6yeyq9xBPq6LpwhJVWCFmUKLlpxPy4cWqhU1aY2Y/65xBN8LZ9Oj80ieyCLZA/54mmJSRCQSBwvkZJK2AnuSReVLVcHXfT02/LCNCnmsFOIuMt0a9hHuXdwEb68iBacgRh8R7S5diWi3gVJQOqk7d+IE8mhqM7otnwAKn2rs/GDKAVXc7NAerG5uhm7cxzPbFOkX4ag2sjY7po3NlzXg76QbRsNZjnJYBGyzUPOG7d/kJMuEf/osQOZIra30lUMJRMT5woAsaqgukJH399GFLVD0ithp0GhtZwG5FdUIcTTlysJAeP/iDl8zw8brW1ug5nYJEuu5p8GEyqqjs3d26KnwA1gP4fVAxIK9MLRTLGt67QskS45y9pnIzDu53JOpw86D43S7rwv5msQN4kPk3I0b4io/n2YGEaDDNPdP4LaaefXjm8RpXT59Oc1JSyRM+FIEYHz/ea1iK3xC27Yfg2AYVq5A1PiY8RJnNP/6Z++CLH87wbU=